stages:
  - pull

mart-ecr:
  stage: pull
  tags:
    - new_mytm_dev
  variables:
    GIT_STRATEGY: none

  script:
    - cd /www/wwwroot/ECR/ecr-mart
    - git pull origin main
    - ./redeploy.sh
    - echo "Mart ECR updated, migrated and deployed successfully"

  only:
    - main
