using ClosedXML.Excel;

namespace BaqalaPOS.Api.Services;

/// <summary>Real .xlsx export shared by all HRM report/list endpoints — FRD's "Excel mandatory"
/// export rule, with a metadata header block (title, filter summary, generated by/at, branch,
/// record count) above the data table, per FRD 4.4/19.</summary>
public static class ExcelWriter
{
    public static byte[] Write(
        string title, string filterSummary, string[] headers, IReadOnlyList<object?[]> rows,
        string? generatedBy = null, string? branch = null)
    {
        using var workbook = new XLWorkbook();
        var sheet = workbook.Worksheets.Add(Sanitize(title));

        var row = 1;
        sheet.Cell(row, 1).Value = title;
        sheet.Cell(row, 1).Style.Font.Bold = true;
        sheet.Cell(row, 1).Style.Font.FontSize = 14;
        row++;

        if (!string.IsNullOrWhiteSpace(filterSummary))
        {
            sheet.Cell(row, 1).Value = filterSummary;
            sheet.Cell(row, 1).Style.Font.FontColor = XLColor.FromHtml("#666666");
            row++;
        }

        var meta = new List<string> { $"Generated: {DateTime.UtcNow:dd MMM yyyy HH:mm} UTC", $"Records: {rows.Count}" };
        if (!string.IsNullOrWhiteSpace(generatedBy)) meta.Insert(0, $"Generated by: {generatedBy}");
        if (!string.IsNullOrWhiteSpace(branch)) meta.Add($"Branch: {branch}");
        sheet.Cell(row, 1).Value = string.Join("  ·  ", meta);
        sheet.Cell(row, 1).Style.Font.FontColor = XLColor.FromHtml("#888888");
        sheet.Cell(row, 1).Style.Font.FontSize = 9;
        row += 2;

        var headerRow = row;
        for (var c = 0; c < headers.Length; c++)
        {
            var cell = sheet.Cell(headerRow, c + 1);
            cell.Value = headers[c];
            cell.Style.Font.Bold = true;
            cell.Style.Font.FontColor = XLColor.White;
            cell.Style.Fill.BackgroundColor = XLColor.FromHtml("#111111");
        }
        row++;

        foreach (var dataRow in rows)
        {
            for (var c = 0; c < dataRow.Length; c++)
                SetCell(sheet.Cell(row, c + 1), dataRow[c]);
            row++;
        }

        sheet.Columns(1, headers.Length).AdjustToContents();
        sheet.SheetView.FreezeRows(headerRow);

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    private static void SetCell(IXLCell cell, object? value)
    {
        switch (value)
        {
            case null: cell.Value = ""; break;
            case decimal d: cell.Value = d; break;
            case int i: cell.Value = i; break;
            case DateTime dt: cell.Value = dt; cell.Style.DateFormat.Format = "yyyy-mm-dd hh:mm"; break;
            case DateOnly dOnly: cell.Value = dOnly.ToDateTime(TimeOnly.MinValue); cell.Style.DateFormat.Format = "yyyy-mm-dd"; break;
            default: cell.Value = value.ToString() ?? ""; break;
        }
    }

    // Worksheet names can't contain \ / ? * [ ] : and are capped at 31 chars.
    private static string Sanitize(string title)
    {
        var clean = new string(title.Where(c => !"\\/?*[]:".Contains(c)).ToArray());
        return clean.Length > 31 ? clean[..31] : clean;
    }
}
