using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using BaqalaPOS.Api.Data;

#nullable disable

namespace BaqalaPOS.Api.Migrations
{
    [DbContext(typeof(BaqalaDbContext))]
    [Migration("20260703100000_ClearAutoGeneratedProductImages")]
    public class ClearAutoGeneratedProductImages : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // A now-removed startup backfill briefly auto-populated products.image_url
            // with placeholder/looked-up photos. Clear those out so only photos a user
            // explicitly uploads (via Add/Edit Product) are ever stored.
            migrationBuilder.Sql("UPDATE products SET image_url = NULL WHERE image_url IS NOT NULL;");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Data deletion is not reversible
        }
    }
}
